/-
Copyright (c) 2026 Shaun Allison. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Shaun Allison
-/
import KnightModel.KnightAutGroup.GenericFilter
import KnightModel.KnightAutGroup.Basic
import Mathlib
/-!
# The Knight Group

This file assembles the generic automorphisms `genericAut n` into the knight group and
verifies all three `KnightAutGroup` axioms.

`wordToAut` maps words to order automorphisms of `ℚ` by composing `genericAut n` (and
their inverses) according to the letters.  The two key lemmas connecting forcing to the
automorphisms are:
- `wordToAut_eval`: if `p ∈ genericFilter` evaluates `w` from `a` to `b`, then
  `wordToAut w a = b`.
- `wordToAut_fixing`: if `wordToAut w b = b` and `a ≤ b`, then `wordToAut w a = a`.

## Main definitions

* `wordToAut w`: the order automorphism corresponding to a word `w`.
* `knightAutGroup`: the subgroup of `ℚ ≃o ℚ` generated by `{genericAut n | n : ℕ}`.

## Main results

* `wordToAut_eval`, `evalWord_of_wordToAut`: the bridge between forcing and automorphisms.
* `wordToAut_fixing`: the fixing property for `wordToAut`, lifting `evalWord_fixing`.
* `knightAutGroup.transitivity`, `knightAutGroup.fixing`, `knightAutGroup.density`:
  the three `KnightAutGroup` axioms are verified for `knightAutGroup`.

## Tags

knight group, wordToAut, generic automorphism, transitivity, fixing, density
-/

section WordToAut

open OrderDual

/-- The order automorphism corresponding to a word: forward letters contribute `genericAut n`,
    inverse letters contribute `(genericAut n)⁻¹`, composed left-to-right. -/
noncomputable def wordToAut : Word → ℚ ≃o ℚ
  | [] => OrderIso.refl ℚ
  | (n, false) :: w => wordToAut w * genericAut n
  | (n, true) :: w => wordToAut w * (genericAut n)⁻¹

/-- `wordToAut w` lies in `Subgroup.closure (Set.range genericAut)`. -/
lemma wordToAut_mem_closure (w : Word) :
    (wordToAut w : ℚ ≃o ℚ) ∈ Subgroup.closure (Set.range genericAut) := by
  induction w with
  | nil =>
    simp only [wordToAut]
    exact Subgroup.one_mem _
  | cons l w ih =>
    obtain ⟨n, bl⟩ := l
    cases bl
    · simp only [wordToAut]
      exact Subgroup.mul_mem _ ih (Subgroup.subset_closure ⟨n, rfl⟩)
    · simp only [wordToAut]
      exact Subgroup.mul_mem _ ih (Subgroup.inv_mem _ (Subgroup.subset_closure ⟨n, rfl⟩))

/-- If `evalWord p w a = some b` for some `p ∈ genericFilter`, then `wordToAut w a = b`. -/
lemma wordToAut_eval (w : Word) (p : KnightCondition) (hp : p ∈ genericFilter)
    (a b : ℚ) (h : evalWord p w a = some b) : wordToAut w a = b := by
  induction w generalizing a with
  | nil =>
    simp only [evalWord] at h
    simp only [wordToAut, OrderIso.refl_apply]
    exact Option.some.inj h
  | cons l w ih =>
    obtain ⟨n, bl⟩ := l
    -- Case-split first so simp can reduce the evalLetter pattern match
    cases bl
    · -- Forward letter (n, false)
      simp only [evalWord, evalLetter] at h
      -- h : (p.seq n).apply? a >>= evalWord p w = some b
      cases hc : (p.seq n).apply? a with
      | none => simp [hc] at h
      | some c =>
        rw [hc] at h
        have hmem := PartialInj.mem_graph_of_apply? hc
        have hgaut : genericAut n a = c := genericAut_spec n p hp a c hmem
        change wordToAut w (genericAut n a) = b
        rw [hgaut]; exact ih c h
    · -- Inverse letter (n, true)
      simp only [evalWord, evalLetter] at h
      -- h : (p.seq n).inv.apply? a >>= evalWord p w = some b
      cases hc : (p.seq n).inv.apply? a with
      | none => simp [hc] at h
      | some c =>
        rw [hc] at h
        have hmem := PartialInj.mem_graph_of_apply? hc
        simp only [FixingPartialAut.inv, PartialIso.symm, PartialInj.symm,
                   Set.mem_setOf_eq] at hmem
        have hgaut : genericAut n c = a := genericAut_spec n p hp c a hmem
        have hgaut_inv : (genericAut n)⁻¹ a = c := by simp [← hgaut]
        change wordToAut w ((genericAut n)⁻¹ a) = b
        rw [hgaut_inv]; exact ih c h

/-- `wordToAut (w₁ ++ w₂) = wordToAut w₂ * wordToAut w₁`. -/
lemma wordToAut_append (w₁ w₂ : Word) :
    wordToAut (w₁ ++ w₂) = wordToAut w₂ * wordToAut w₁ := by
  induction w₁ with
  | nil => simp [wordToAut]; rfl
  | cons l w₁ ih =>
    obtain ⟨n, bl⟩ := l
    cases bl
    · simp only [List.cons_append, wordToAut, ih, mul_assoc]
    · simp only [List.cons_append, wordToAut, ih, mul_assoc]

/-- `wordToAut w⁻¹ = (wordToAut w)⁻¹`. -/
lemma wordToAut_wordInv (w : Word) : wordToAut w⁻¹ = (wordToAut w)⁻¹ := by
  have hnil : wordToAut ([] : Word) = 1 := by simp only [wordToAut]; rfl
  induction w with
  | nil =>
    have hnil_inv : ([] : Word)⁻¹ = [] := by change wordInv [] = []; simp [wordInv]
    rw [hnil_inv, hnil, inv_one]
  | cons l w ih =>
    obtain ⟨n, bl⟩ := l
    cases bl
    · -- Forward letter (n, false): word inverse is w⁻¹ ++ [(n, true)]
      have hinv : ((n, false) :: w)⁻¹ = (w⁻¹ ++ [(n, true)] : Word) := by
        change wordInv ((n, false) :: w) = wordInv w ++ [(n, true)]
        simp only [wordInv, List.map_cons, List.reverse_cons]
        rfl
      have ht : wordToAut ([(n, true)] : Word) = (genericAut n)⁻¹ := by
        change wordToAut [] * (genericAut n)⁻¹ = (genericAut n)⁻¹
        rw [hnil, one_mul]
      have hcons : wordToAut ((n, false) :: w) = wordToAut w * genericAut n := rfl
      rw [hinv, wordToAut_append, ih, ht, hcons, mul_inv_rev]
    · -- Inverse letter (n, true): word inverse is w⁻¹ ++ [(n, false)]
      have hinv : ((n, true) :: w)⁻¹ = (w⁻¹ ++ [(n, false)] : Word) := by
        change wordInv ((n, true) :: w) = wordInv w ++ [(n, false)]
        simp only [wordInv, List.map_cons, List.reverse_cons]
        rfl
      have hf : wordToAut ([(n, false)] : Word) = genericAut n := by
        change wordToAut [] * genericAut n = genericAut n
        rw [hnil, one_mul]
      have hcons : wordToAut ((n, true) :: w) = wordToAut w * (genericAut n)⁻¹ := rfl
      rw [hinv, wordToAut_append, ih, hf, hcons, mul_inv_rev, inv_inv]

/-- Every element of `Subgroup.closure (Set.range genericAut)` is `wordToAut w` for some word. -/
lemma closure_exists_word (g : ℚ ≃o ℚ)
    (hg : g ∈ Subgroup.closure (Set.range genericAut)) :
    ∃ w : Word, g = wordToAut w :=
  Subgroup.closure_induction
    (p := fun g _ => ∃ w : Word, g = wordToAut w)
    (mem := fun x hx => by
      obtain ⟨n, rfl⟩ := hx
      exact ⟨[(n, false)], by simp only [wordToAut]; exact (one_mul _).symm⟩)
    (one := ⟨[], by simp [wordToAut]; rfl⟩)
    (mul := fun x y _ _ hpx hpy => by
      obtain ⟨w₁, hw₁⟩ := hpx; obtain ⟨w₂, hw₂⟩ := hpy
      exact ⟨w₂ ++ w₁, by rw [hw₁, hw₂]; exact (wordToAut_append w₂ w₁).symm⟩)
    (inv := fun x _ hpx => by
      obtain ⟨w, hw⟩ := hpx
      exact ⟨w⁻¹, by rw [hw]; exact (wordToAut_wordInv w).symm⟩)
    hg

/-- `genericAut n a = b` implies `(a, b) ∈ (genericPartialIso n).graph`. -/
lemma genericAut_mem_graph (n : ℕ) (a b : ℚ) (h : genericAut n a = b) :
    (a, b) ∈ (genericPartialIso n).graph := by
  have hspec := Classical.choose_spec (genericPartialIso_total n a)
  have heq : Classical.choose (genericPartialIso_total n a) = b := by
    simp only [genericAut, PartialIso.toIso] at h
    exact h
  rwa [← heq]

/-- if `wordToAut w b = c` then `∃ p ∈ genericFilter, evalWord p w b = some c`. -/
lemma evalWord_of_wordToAut (w : Word) (b c : ℚ) (h : wordToAut w b = c) :
    ∃ p ∈ genericFilter, evalWord p w b = some c := by
  induction w generalizing b c with
  | nil =>
    simp only [wordToAut, OrderIso.refl_apply] at h
    subst h
    obtain ⟨p₀, hp₀, _⟩ := genericFilter_meets_inDomain 0 0
    exact ⟨p₀, hp₀, by simp [evalWord]⟩
  | cons l w' ih =>
    obtain ⟨n, bl⟩ := l
    cases bl
    · -- Forward letter (n, false): wordToAut ((n, false) :: w') b = wordToAut w' (genericAut n b)
      have h' : wordToAut w' (genericAut n b) = c := h
      obtain ⟨p₁, hp₁, heval₁⟩ := ih (genericAut n b) c h'
      have hmem : (b, genericAut n b) ∈ (genericPartialIso n).graph :=
        genericAut_mem_graph n b (genericAut n b) rfl
      change (b, genericAut n b) ∈ ⋃ p ∈ genericFilter, (p.seq n).graph at hmem
      simp only [Set.mem_iUnion] at hmem
      obtain ⟨p₂, hp₂, h₂⟩ := hmem
      obtain ⟨r, hr, hrp₁, hrp₂⟩ := genericFilter_directed hp₁ hp₂
      have hbb' : (b, genericAut n b) ∈ (r.seq n).graph := hrp₂ n h₂
      have heval_r : evalWord r w' (genericAut n b) = some c :=
        evalWord_le w' (genericAut n b) c hrp₁ heval₁
      have hletter : evalLetter r (n, false) b = some (genericAut n b) := by
        simp only [evalLetter]; exact PartialInj.apply?_of_mem hbb'
      exact ⟨r, hr, by simp only [evalWord, hletter, Option.bind_some]; exact heval_r⟩
    · -- Inverse letter (n, true): wordToAut ((n, true) :: w') b = wordToAut w' ((genericAut n)⁻¹ b)
      have h' : wordToAut w' ((genericAut n)⁻¹ b) = c := h
      obtain ⟨p₁, hp₁, heval₁⟩ := ih ((genericAut n)⁻¹ b) c h'
      set b' := (genericAut n)⁻¹ b
      have hgaut : genericAut n b' = b := (genericAut n).apply_symm_apply b
      have hmem : (b', b) ∈ (genericPartialIso n).graph :=
        genericAut_mem_graph n b' b hgaut
      change (b', b) ∈ ⋃ p ∈ genericFilter, (p.seq n).graph at hmem
      simp only [Set.mem_iUnion] at hmem
      obtain ⟨p₂, hp₂, h₂⟩ := hmem
      obtain ⟨r, hr, hrp₁, hrp₂⟩ := genericFilter_directed hp₁ hp₂
      have hb'b : (b', b) ∈ (r.seq n).graph := hrp₂ n h₂
      have heval_r : evalWord r w' b' = some c :=
        evalWord_le w' b' c hrp₁ heval₁
      have hletter_fwd : evalLetter r (n, false) b' = some b := by
        simp only [evalLetter]; exact PartialInj.apply?_of_mem hb'b
      have hletter : evalLetter r (n, true) b = some b' :=
        evalLetter_letterInv r (n, false) b' b hletter_fwd
      exact ⟨r, hr, by simp only [evalWord, hletter, Option.bind_some]; exact heval_r⟩

/-- Main fixing lemma for words: if `wordToAut w b = b` and `a ≤ b`, then `wordToAut w a = a`. -/
lemma wordToAut_fixing (w : Word) (a b : ℚ) (hab : a ≤ b) (hb : wordToAut w b = b) :
    wordToAut w a = a := by
  -- Find p₁ ∈ genericFilter with evalWord p₁ w b = some b
  obtain ⟨p₁, hp₁, hp₁eval⟩ := evalWord_of_wordToAut w b b hb
  -- Find p₂ ∈ genericFilter with evalWord p₂ w a = some (wordToAut w a)
  obtain ⟨p₂, hp₂, hp₂eval⟩ := evalWord_of_wordToAut w a (wordToAut w a) rfl
  -- Find common extension r with r ≤ p₁ and r ≤ p₂
  obtain ⟨r, hr, hrp₁, hrp₂⟩ := genericFilter_directed hp₁ hp₂
  -- Lift evaluations to r
  have hb_eval : evalWord r w b = some b := evalWord_le w b b hrp₁ hp₁eval
  have ha_eval : evalWord r w a = some (wordToAut w a) :=
    evalWord_le w a (wordToAut w a) hrp₂ hp₂eval
  -- Apply evalWord_fixing: a = wordToAut w a
  exact (KnightCondition.evalWord_fixing w r a b (wordToAut w a) hab hb_eval ha_eval).symm

end WordToAut

/-! ## The Knight Group -/

/-- The Knight group: the subgroup of `ℚ ≃o ℚ` generated by the generic automorphisms. -/
noncomputable def knightAutGroup : KnightAutGroup where
  toSubgroup := Subgroup.closure (Set.range genericAut)
  transitivity := by
    intro a b
    obtain ⟨p, hp, w, hw⟩ := genericFilter_meets_connects a b
    exact ⟨wordToAut w, wordToAut_mem_closure w, wordToAut_eval w p hp a b hw⟩
  fixing := by
    intro a b hab g hg hgb
    obtain ⟨w, rfl⟩ := closure_exists_word g hg
    exact wordToAut_fixing w a b hab hgb
  density := by
    intro a b c hab hbc
    obtain ⟨p, hp, w, hw_a, d, hw_c, hdb⟩ := genericFilter_meets_decrements a b c hab hbc
    exact ⟨wordToAut w, wordToAut_mem_closure w,
           wordToAut_eval w p hp a a hw_a,
           lt_of_eq_of_lt (wordToAut_eval w p hp c d hw_c) hdb⟩
